"""
app/embeddings/embedding_service.py
===================================
Service orchestrator for the Embedding Pipeline.

PURPOSE:
    Coordinates loading chunk data, executing validation logic, batching texts
    for model inference, validating vector outputs, and uploading payload-bound
    vectors to Qdrant. Finally, calculates run statistics and saves them.

SOLID: Single Responsibility — coordinates the steps of the embedding pipeline.
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any, Dict, List

from app.core.exceptions import EmbeddingError, VectorStoreError
from app.embeddings.embedding_logger import embedding_log
from app.embeddings.embedding_models import EmbeddingStatistics
from app.embeddings.embedding_repository import EmbeddingRepository
from app.embeddings.embedder import BGEEmbedder
from app.embeddings.embedding_utils import (
    detect_duplicates,
    validate_chunk_metadata,
    validate_embedding_dimension,
)
from app.models.document import DocumentChunk
from app.repositories.vector_repository import VectorRepository


class EmbeddingService:
    """
    Orchestration service for the embedding generation and indexing pipeline.
    """

    def __init__(
        self,
        embedder: BGEEmbedder,
        repository: EmbeddingRepository,
        vector_repository: VectorRepository,
    ) -> None:
        """
        Initialize the embedding service with required adapters.
        """
        self.embedder = embedder
        self.repository = repository
        self.vector_repository = vector_repository

    async def embed_document(self, document_id: str, batch_size: int = 32) -> EmbeddingStatistics:
        """
        Process the embedding pipeline for a single document.

        Loads chunks generated by the chunking module, runs validation,
        generates embeddings, and upserts them into Qdrant.

        Args:
            document_id: UUID of the document.
            batch_size: Size of batches to send to model.

        Returns:
            EmbeddingStatistics object representing execution metrics.
        """
        embedding_log.info(
            "Embedding pipeline started | doc_id={doc_id} | batch_size={batch_size}",
            doc_id=document_id,
            batch_size=batch_size,
        )

        try:
            raw_chunks = self.repository.load_document_chunks(document_id)
        except Exception as exc:
            embedding_log.error(
                "Failed to load document chunks | doc_id={doc_id} | error={error}",
                doc_id=document_id,
                error=str(exc),
            )
            raise

        return await self.embed_chunks_list(raw_chunks, batch_size)

    async def embed_chunks_list(self, raw_chunks: List[Dict[str, Any]], batch_size: int = 32) -> EmbeddingStatistics:
        """
        Processes a raw list of chunk dictionaries.
        """
        start_time = time.perf_counter()
        total_chunks = len(raw_chunks)
        embedded_count = 0
        failed_count = 0

        embedding_log.info("Processing chunks batch by batch | total_chunks={count}", count=total_chunks)

        # 1. Duplicate detection
        unique_chunks, duplicate_ids = detect_duplicates(raw_chunks)
        if duplicate_ids:
            embedding_log.warning(
                "Duplicate chunk IDs filtered out | count={count} | ids={ids}",
                count=len(duplicate_ids),
                ids=list(duplicate_ids)[:5],
            )
            failed_count += len(duplicate_ids)

        # 2. Metadata validation
        valid_chunks: List[DocumentChunk] = []
        for raw_chunk in unique_chunks:
            errors = validate_chunk_metadata(raw_chunk)
            if errors:
                embedding_log.error(
                    "Chunk metadata validation failed | chunk_id={chunk_id} | errors={errors}",
                    chunk_id=raw_chunk.get("chunk_id", "unknown"),
                    errors=errors,
                )
                failed_count += 1
                continue

            # Convert dict to domain entity DocumentChunk safely
            try:
                page_num = raw_chunk.get("page_number") or raw_chunk.get("page")
                doc_chunk = DocumentChunk(
                    chunk_id=raw_chunk["chunk_id"],
                    document_id=raw_chunk["document_id"],
                    document_name=raw_chunk["document_name"],
                    category=raw_chunk["category"],
                    page_number=int(page_num) if page_num is not None else 1,
                    chunk_index=int(raw_chunk["chunk_index"]),
                    text=raw_chunk["text"],
                    char_count=raw_chunk.get("char_count", len(raw_chunk["text"])),
                    source=raw_chunk.get("source", raw_chunk["document_name"]),
                    metadata=raw_chunk["metadata"],
                )
                valid_chunks.append(doc_chunk)
            except Exception as exc:
                embedding_log.error(
                    "Failed to parse chunk to DocumentChunk | chunk_id={chunk_id} | error={error}",
                    chunk_id=raw_chunk.get("chunk_id", "unknown"),
                    error=str(exc),
                )
                failed_count += 1

        # 3. Batch processing and embedding generation
        valid_chunks_count = len(valid_chunks)
        batch_times: List[float] = []

        for i in range(0, valid_chunks_count, batch_size):
            batch = valid_chunks[i : i + batch_size]
            batch_num = (i // batch_size) + 1
            embedding_log.info(
                "Embedding batch | number={batch_num} | size={size}",
                batch_num=batch_num,
                size=len(batch),
            )

            batch_texts = [chunk.text for chunk in batch]
            batch_start = time.perf_counter()

            try:
                # Generate embeddings
                embeddings = self.embedder.embed_documents(batch_texts)
            except EmbeddingError as exc:
                embedding_log.error(
                    "Model embedding generation failed for batch={batch_num} | error={error}",
                    batch_num=batch_num,
                    error=str(exc),
                )
                failed_count += len(batch)
                continue

            batch_elapsed = time.perf_counter() - batch_start
            batch_times.append(batch_elapsed)

            # Validate dimensions and store vectors
            valid_batch_chunks: List[DocumentChunk] = []
            valid_batch_embeddings: List[List[float]] = []

            for chunk, emb in zip(batch, embeddings):
                if not validate_embedding_dimension(emb, expected_dim=384):
                    embedding_log.error(
                        "Embedding dimension mismatch | chunk_id={chunk_id} | dimension={dim}",
                        chunk_id=chunk.chunk_id,
                        dim=len(emb),
                    )
                    failed_count += 1
                    continue

                valid_batch_chunks.append(chunk)
                valid_batch_embeddings.append(emb)

            # Store in Qdrant
            if valid_batch_chunks:
                try:
                    await self.vector_repository.upsert_chunks(
                        chunks=valid_batch_chunks,
                        embeddings=valid_batch_embeddings,
                    )
                    embedded_count += len(valid_batch_chunks)
                    embedding_log.info(
                        "Batch successfully indexed | batch={batch_num} | indexed={count} | time={time:.2f}s",
                        batch_num=batch_num,
                        count=len(valid_batch_chunks),
                        time=batch_elapsed,
                    )
                except VectorStoreError as exc:
                    embedding_log.error(
                        "Qdrant indexing failed for batch={batch_num} | error={error}",
                        batch_num=batch_num,
                        error=str(exc),
                    )
                    failed_count += len(valid_batch_chunks)

        # 4. Generate statistics
        total_duration = time.perf_counter() - start_time
        avg_time = (total_duration / total_chunks) if total_chunks > 0 else 0.0

        stats = EmbeddingStatistics(
            total_chunks=total_chunks,
            embedded_chunks=embedded_count,
            failed_chunks=failed_count,
            average_embedding_time=avg_time,
            embedding_dimension=384,
            processed_at=datetime.now(timezone.utc),
        )

        # Save stats
        try:
            self.repository.save_embedding_statistics(stats)
        except Exception as exc:
            embedding_log.error("Failed to save run statistics | error={error}", error=str(exc))

        embedding_log.info(
            "Embedding pipeline finished | total={total} | embedded={embedded} | failed={failed} | time={duration:.2f}s",
            total=total_chunks,
            embedded=embedded_count,
            failed=failed_count,
            duration=total_duration,
        )

        return stats
